version: "3.3"
services:
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: iot-project-mid-led
    container_name: iot-project-mid-led
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    env_file: .env
    ports:
      # host:docker
      - "5000:5000"
