name: Build and Publish Server Docker

on:
  push:
    branches: [ main ]
    paths-ignore: ["README.md", "embedded/**"]

jobs:
  buildpush:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip docker]') }}
    env:
      IMAGE_NAME: "iot-project-mid-led"
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'test-server'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - id: reponame
        name: Lowercase the Docker Registry Repo Name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: 'Build image and push to Docker Hub and GitHub Container Registry'
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.reponame.outputs.lowercase }}:latest